name: Waka Readme

on:
  
  workflow_dispatch:
  schedule:
    
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True" 
          SHOW_OS: "True" 
          SHOW_PROJECTS: "True" 
          SHOW_TOTAL_CODE_TIME: "True" 
          SHOW_COMMIT: "True" 
          SHOW_PROFILE_VIEWS: "True" 
          SHOW_DAYS_OF_WEEK: "True"  
          SHOW_LANGUAGE: "True" 
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True" 
          SHOW_SHORT_INFO: "True" 
          SHOW_LOC_CHART: "True" 
          SYMBOL_VERSION: "2" 
